# Generated by Django 3.2.20 on 2023-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_session',
            name='place',
            field=models.TextField(default='Anywhere'),
        ),
        migrations.AddField(
            model_name='workout_session',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workout_session',
            name='instructors',
            field=models.TextField(),
        ),
    ]
