# Generated by Django 3.2.20 on 2023-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20230723_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_session',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
